"""
Domain models for pipeline configurations.

These Pydantic models represent the serialised form of a pipeline as
created by the drag-and-drop canvas.  Every save / load / export operation
works with these models.

A pipeline is a directed acyclic graph (DAG) of nodes connected by edges.

    PipelineConfig
    ├── nodes: list[NodeConfig]    ← one per draggable block
    └── edges: list[EdgeConfig]    ← one per drawn connection

The pipeline compiler reads a ``PipelineConfig`` and produces an execution
plan.  The pipeline executor runs that plan node by node.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, model_validator

from app.core.constants import ExecutionStatus, NodeCategory, NodeExecutionStatus


# --------------------------------------------------------------------------- #
# Node position (canvas layout)
# --------------------------------------------------------------------------- #


class NodePosition(BaseModel):
    """
    The (x, y) position of a node on the React Flow canvas.

    Stored so the layout is preserved when a pipeline is saved and reloaded.
    """

    x: float = Field(default=0.0, description="Horizontal position in canvas units.")
    y: float = Field(default=0.0, description="Vertical position in canvas units.")


# --------------------------------------------------------------------------- #
# Node configuration
# --------------------------------------------------------------------------- #


class NodeConfig(BaseModel):
    """
    The configuration of a single node within a pipeline.

    Attributes
    ----------
    id:
        Unique identifier for this node *within* the pipeline.  This is
        generated by the frontend when the user drags a node onto the canvas.
    type:
        The node type string (e.g. ``"pdf_loader"``).  Must match a key in
        the ``NodeRegistry``.
    position:
        Canvas position for layout persistence.
    config:
        A dictionary of user-supplied configuration values for this node.
        Keys correspond to ``NodeField.name`` values in the node's schema.
    label:
        Optional user-friendly display label (defaults to the node's
        display name if not set).
    notes:
        Optional freeform notes the user attaches to the node.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique node instance ID within the pipeline.",
    )
    type: str = Field(description="Node type key (must be in the NodeRegistry).")
    position: NodePosition = Field(
        default_factory=NodePosition,
        description="Canvas position for layout.",
    )
    config: dict[str, Any] = Field(
        default_factory=dict,
        description="User-supplied config values keyed by field name.",
    )
    label: str | None = Field(
        default=None,
        description="Optional custom display label for this node instance.",
    )
    notes: str | None = Field(
        default=None,
        description="Optional user notes attached to this node.",
    )


# --------------------------------------------------------------------------- #
# Edge configuration
# --------------------------------------------------------------------------- #


class EdgeConfig(BaseModel):
    """
    A directed connection between two node ports.

    Attributes
    ----------
    id:
        Unique identifier for this edge.
    source_node_id:
        ID of the upstream (output) node.
    source_port:
        Name of the output port on the source node.
    target_node_id:
        ID of the downstream (input) node.
    target_port:
        Name of the input port on the target node.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique edge identifier.",
    )
    source_node_id: str = Field(description="ID of the upstream node.")
    source_port: str = Field(description="Output port name on the source node.")
    target_node_id: str = Field(description="ID of the downstream node.")
    target_port: str = Field(description="Input port name on the target node.")

    @model_validator(mode="after")
    def source_and_target_differ(self) -> "EdgeConfig":
        """Prevent self-loops."""
        if self.source_node_id == self.target_node_id:
            raise ValueError("An edge cannot connect a node to itself.")
        return self


# --------------------------------------------------------------------------- #
# Pipeline configuration
# --------------------------------------------------------------------------- #


class PipelineConfig(BaseModel):
    """
    The complete, serialisable configuration of a RAG pipeline.

    This is the canonical data structure that travels between the frontend
    canvas and the backend pipeline engine.  It is persisted as JSON in
    ``data/pipelines/`` and can be exported / imported by users.

    Attributes
    ----------
    id:
        Unique pipeline identifier.
    name:
        User-assigned display name.
    description:
        Optional description of what this pipeline does.
    nodes:
        All node instances in the pipeline.
    edges:
        All connections between node ports.
    created_at:
        UTC creation timestamp.
    updated_at:
        UTC last-modified timestamp.
    tags:
        Optional user-assigned tags for filtering in the gallery.
    is_template:
        When True this config is shown in the template gallery.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique pipeline ID.",
    )
    name: str = Field(description="Pipeline display name.")
    description: str | None = Field(
        default=None,
        description="Optional description of the pipeline's purpose.",
    )
    nodes: list[NodeConfig] = Field(
        default_factory=list,
        description="All node instances in the pipeline.",
    )
    edges: list[EdgeConfig] = Field(
        default_factory=list,
        description="All connections between node ports.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    tags: list[str] = Field(default_factory=list)
    is_template: bool = Field(default=False)
    version: str = Field(
        default="1",
        description="Schema version for forward-compatibility.",
    )

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def get_node(self, node_id: str) -> NodeConfig | None:
        """Return the NodeConfig with the given ID, or None."""
        for node in self.nodes:
            if node.id == node_id:
                return node
        return None

    def get_node_ids(self) -> list[str]:
        """Return all node IDs in this pipeline."""
        return [n.id for n in self.nodes]

    def get_edges_from(self, node_id: str) -> list[EdgeConfig]:
        """Return all edges whose source is ``node_id``."""
        return [e for e in self.edges if e.source_node_id == node_id]

    def get_edges_to(self, node_id: str) -> list[EdgeConfig]:
        """Return all edges whose target is ``node_id``."""
        return [e for e in self.edges if e.target_node_id == node_id]

    def touch(self) -> None:
        """Update ``updated_at`` to now."""
        self.updated_at = datetime.now(timezone.utc)


# --------------------------------------------------------------------------- #
# Execution tracking models
# --------------------------------------------------------------------------- #


class NodeExecutionRecord(BaseModel):
    """
    Runtime state and timing for a single node within one pipeline execution.
    """

    node_id: str
    node_type: str
    status: NodeExecutionStatus = NodeExecutionStatus.WAITING
    started_at: datetime | None = None
    completed_at: datetime | None = None
    error: str | None = None
    output_preview: dict[str, Any] = Field(
        default_factory=dict,
        description="Truncated preview of this node's outputs (for the UI log).",
    )

    @property
    def duration_ms(self) -> float | None:
        """Wall-clock execution time in milliseconds."""
        if self.started_at and self.completed_at:
            delta = self.completed_at - self.started_at
            return delta.total_seconds() * 1000
        return None


class PipelineExecutionRecord(BaseModel):
    """
    Runtime tracking record for a complete pipeline execution.

    Created when a pipeline starts and updated as each node completes.
    Sent to the frontend via WebSocket so the canvas can show per-node
    status badges in real time.
    """

    execution_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
    )
    pipeline_id: str
    pipeline_name: str
    status: ExecutionStatus = ExecutionStatus.PENDING
    started_at: datetime | None = None
    completed_at: datetime | None = None
    error: str | None = None
    node_records: dict[str, NodeExecutionRecord] = Field(
        default_factory=dict,
        description="Keyed by node_id.",
    )
    inputs: dict[str, Any] = Field(
        default_factory=dict,
        description="User-supplied pipeline inputs (e.g. the query string).",
    )
    outputs: dict[str, Any] = Field(
        default_factory=dict,
        description="Final pipeline outputs after all nodes complete.",
    )

    @property
    def duration_ms(self) -> float | None:
        if self.started_at and self.completed_at:
            return (self.completed_at - self.started_at).total_seconds() * 1000
        return None
